[package]
name = "dfvstritus"
authors = ["s.a.tanja@student.tue.nl"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
lto = true
opt-level = 3

[[bin]]
name = "debugtritus"
path = "src/bin-debug.rs"

[[bin]]
name = "dfvstritus"
path = "src/main.rs"